# MC Paint mod definition file
modLoader="javafml"
loaderVersion="[26,)"
issueTrackerURL="https://github.com/ichttt/mcpaint"
displayURL="https://minecraft.curseforge.com/projects/mc-paint"
logoFile="mcpaint_logo.png" #optional
authors="ichttt"
[[mods]]
    modId="mcpaint"
    version="${file.jarVersion}"
    displayName="Mc Paint"
    description='''Paint your blocks the way you want them to be!
The mod adds two items, a brush and a stamp. The brush can be crafted like a pickaxe but with wool instead of your pickaxe material at the top.
Right-click any block with the brush and a editor will pop up where you can paint it!
The resolution can be changed from 8x8 up to 128x128 for a single block.'''
[[dependencies.mcpaint]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1,1.17)"
    ordering="NONE"
    side="BOTH"
#[[dependencies.mcpaint]]
#    modId="forge"
#    mandatory=true
#    versionRange="[28.1.0,)"
#    ordering="NONE"
#    side="BOTH"